- First, we will import the libraries, loading the dataset and understanding the data.

In [1]:
# first import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# setting maximum rows & columns display size to 200 for better visibility of data
pd.set_option('display.max_columns', 200)

In [3]:
# load the dataset 
main_df = pd.read_csv('../data/Sample - Superstore.csv',encoding='ISO-8859-1')
main_df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
# checking the data types of all the columns
main_df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [5]:
# check the descriptive statistics of numerical variables
main_df[["Sales", "Profit", "Quantity", "Discount"]].describe()

              Sales       Profit     Quantity     Discount
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001    28.656896     3.789574     0.156203
std      623.245101   234.260108     2.225110     0.206452
min        0.444000 -6599.978000     1.000000     0.000000
25%       17.280000     1.728750     2.000000     0.000000
50%       54.490000     8.666500     3.000000     0.200000
75%      209.940000    29.364000     5.000000     0.200000
max    22638.480000  8399.976000    14.000000     0.800000

- Some extreme outliers exist in sales and profit.

- Next we will check null values per column.

In [6]:
null_val = main_df.isnull().sum()
null_val

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

- We will check if there are any duplicates.

In [7]:
has_duplicates = main_df.duplicated().any()
has_duplicates

np.False_

- Next we will perform data cleaning.

- First we will convert Order Date & Ship Date into date data type.

In [8]:
main_df['Order Date'] = pd.to_datetime(main_df['Order Date'])
main_df['Ship Date'] = pd.to_datetime(main_df['Ship Date'])

main_df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

- Next we will perform outlier analysis.

In [9]:
outlier_cols = ['Postal Code','Sales','Quantity','Discount','Profit']

def find_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    return len(outliers), lower, upper

# Summary
outlier_summary = []
for col in outlier_cols:
    n_out, low, up = find_outliers(main_df, col)
    pct = n_out / len(main_df) * 100
    outlier_summary.append({
        'Column': col,
        'Outliers': n_out,
        '%': round(pct, 2),
        'Lower': round(low, 2),
        'Upper': round(up, 2)
    })

summary_df = pd.DataFrame(outlier_summary)
print(summary_df)

        Column  Outliers      %     Lower      Upper
0  Postal Code         0   0.00 -76954.50  190185.50
1        Sales      1167  11.68   -271.71     498.93
2     Quantity       170   1.70     -2.50       9.50
3     Discount       856   8.57     -0.30       0.50
4       Profit      1881  18.82    -39.72      70.82

- We will now investigate as to why Sales, Quantity, Discount & Profit columns have these outliers.

- Why does Profit have around 18 % outliers?
- Are high discounts resulting in negative profits?

In [10]:
main_df.groupby("Discount")["Profit"].mean()

Discount
0.00     66.900292
0.10     96.055074
0.15     27.288298
0.20     24.702572
0.30    -45.679636
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -101.796797
Name: Profit, dtype: float64

- It can be seen that discounts > 30 % results in a negative profit.

- Why does Sales have around 11 % outliers.
- We will look at the top 5% sales to better understand these transactions.

In [11]:
high_sales = main_df[main_df["Sales"] > main_df["Sales"].quantile(0.95)]
high_sales[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales    Quantity    Discount       Profit
count    500.000000  500.000000  500.000000   500.000000
mean    2042.904070    5.830000    0.135560   303.007548
std     1904.148625    2.535737    0.168581   962.635073
min      957.577500    1.000000    0.000000 -6599.978000
25%     1136.650000    4.000000    0.000000    83.703250
50%     1465.305000    5.000000    0.100000   265.519350
75%     2153.307000    7.000000    0.200000   469.396800
max    22638.480000   14.000000    0.800000  8399.976000

- The max amount of sales & profit seems to very high.
- In retail this is absolutely normal.
- The max quantity of 14 is also absolutely normal.

- Next we will check if most of the high sales are profitable
- If result is around 0.8 -> 80% are profitable, we will keep them.
- If they are negative, we will investigate further.

In [12]:
(high_sales["Profit"] > 0).mean()

np.float64(0.818)

- We will also check if there are any negative values that exist in Profit, Sales & Quantity columns.
- We will ignore Profit since it is possible for profit to be negative.

In [13]:
main_df[main_df["Sales"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [14]:
main_df[main_df['Quantity'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [15]:
main_df[main_df['Discount'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [18]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sqlalchemy import create_engine

# Connect to MySQL
engine = create_engine(
    "mysql+pymysql://root:root@127.0.0.1:3306/retail_db"
)

# Standardize the column names in your DataFrame (space & hyphens)
main_df.columns = [c.replace(' ', '_').replace('-', '_').lower() for c in main_df.columns]

# Load into staging table
main_df.to_sql(
    name="stg_superstore",
    con=engine,
    if_exists="append",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!

In [29]:
unique_years = main_df['order_date'].dt.year.unique()
unique_years

array([2016, 2015, 2014, 2017], dtype=int32)